Codesk/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('userprofile.urls')),
    path('', include("uploader.urls")),
    path('', include('note.urls')),
    path('', include('questions.urls')),
    path('', RedirectView.as_view(url='home')),
    path('home/', Home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Codesk/note/urls.py
from django.urls import path

from note import views

urlpatterns = [
    path('notelist/', views.notelist , name='notelist'),
    path('note/', views.note, name='note')
]

Codesk/uploader/urls.py
from django.urls import path
from uploader import views

urlpatterns = [
    path('uploadquestion/',views.uploadquestion,name="uploadquestion"),
    path('uploadnotes/',views.upload_multiple_files,name="uploadnotes"),
]

Codesk/uploader/models.py
from django.db import models
from core import utils
import hashlib
from PIL import Image
import pytesseract


class ImageFileManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(models.Q(internal_reference__icontains=query) |
                                          models.Q(name__icontains=query) |
                                          models.Q(description__icontains=query)
                                          )


class ImageFile(models.Model):

    name = models.CharField("Name", max_length=100)
    internal_reference = models.CharField("Internal Reference", max_length=100, editable=False)
    description = models.TextField("Description", blank=True, null=True)
    image = models.ImageField(upload_to="OCR_image/input/", verbose_name="Input Image")
    create_at = models.DateTimeField("Create at", auto_now_add=True)
    updated_at = models.DateTimeField("Update at", auto_now=True)

    def __str__(self):
        return "{0:03d} - {1}".format(self.id, self.image)

    def execute_and_save_ocr(self):
        import time
        start_time = time.time()

        img = Image.open(self.image)
        txt = pytesseract.image_to_string(img, lang='eng')
        execution_time = time.time() - start_time
        ocr_txt = OCRText(image = self, text = txt, lang = "EN", execution_time = execution_time)
        ocr_txt.save()

        print("The image {0} was opened.".format(self.image))
        print('OCR: \n{0}\n'.format(txt))
        print('Execution Time: {0}'.format(ocr_txt.execution_time))

        return ocr_txt

    """
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('course_details', args=[], kwargs={'slug': self.slug})
    """

    def save(self, *args, **kwargs):

        if not self.internal_reference:
            random_value = utils.random_value_generator(size=20)
            while ImageFile.objects.filter(internal_reference=random_value).exists():
                random_value = utils.random_value_generator(size=20)
            hash_value = hashlib.md5(bytes(str(self.id) + str(random_value), 'utf-8'))
            self.internal_reference = hash_value.hexdigest()
        super(ImageFile, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "ImageFile"
        verbose_name_plural = "ImageFiles"
        ordering = ['id']

    objects = ImageFileManager()


class OCRText(models.Model):
    text = models.TextField("OCR text", blank=True)
    lang = models.TextField("Language", default="EN")
    execution_time = models.IntegerField("Execution Time", editable=False, null=True);
    image = models.ForeignKey('ImageFile', on_delete=models.CASCADE)
    create_at = models.DateTimeField("Create at", auto_now_add=True)
    updated_at = models.DateTimeField("Update at", auto_now=True)

    def __str__(self):
        return "{0:03d} - {1}".format(self.id, self.image.internal_reference)

    class Meta:
        verbose_name = "OCRText"
        verbose_name_plural = "OCRTexts"
        ordering = ['id']

Codesk/uploader/forms.py
from django import forms
from uploader.models import ImageFile


class ImageFileForm(forms.ModelForm):
    class Meta:
        model = ImageFile
        fields = ('image', )

class UploadFileForm(forms.Form):
    file = forms.FileField()
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

Codesk/uploader/views.py
from django.shortcuts import render, redirect
from uploader.forms import ImageFileForm, UploadFileForm
from uploader.models import ImageFile
import pytesseract
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import ensure_csrf_cookie
from API import search, upload

def uploadquestion(request):
    if request.method == "POST":
        if 'searchword' in request.POST:
            context = search.searchbar(request)
            return render(request, 'results.html', context)

    if request.method == 'POST':
        if 'submitqn' in request.POST:
            upload.uploadQn(request)
            return render(request, "uploader/index.html")


    data = dict()
    pytesseract.pytesseract.tesseract_cmd = 'C:\Program Files\Tesseract-OCR\\tesseract.exe'
    image_form = ImageFileForm(request.POST or None, request.FILES or None)
    print(image_form.is_valid())

    if ImageFile.objects.count() > 0:
        ImageFile.objects.all().delete()

    if image_form.is_valid():
        image = image_form.save()
        image.execute_and_save_ocr()
        redirect('uploadquestion')
    image_last = ImageFile.objects.last()
    image_list = ImageFile.objects.all().order_by('-id')

    data['image_form'] = image_form
    data['image_list'] = image_list
    data['image_last'] = image_last
    return render(request, "uploader/index.html", data)

@ensure_csrf_cookie
def upload_multiple_files(request):
    if request.method == 'POST':
        if 'searchword' in request.POST:
            context = search.searchbar(request)
            return render(request, 'results.html', context)
        else:   
            form = UploadFileForm(request.POST, request.FILES)
            files = request.FILES.getlist('files')
            if form.is_valid():
                for f in files:
                    handle_uploaded_file(f)
                context = {'msg' : '<span style="color: green;">File successfully uploaded</span>'}
                return render(request, "uploader/multiple.html", context)
    else:
        form = UploadFileForm()
    return render(request, 'uploader/multiple.html', {'form': form})

def handle_uploaded_file(f):
    with open(f.name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

Codesk/templates/uploader/index.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %} uploadquestion {% endblock %}

{% block extrahead %} {% endblock %}

{% block extrastyle %}
    <style>

        .clickable_img:hover {
            cursor: pointer;
        }
    </style>

{% endblock %}

{% block extrascript %}
    <script>
        $('.custom-file-input').on('change', function() {
            let fileName = $(this).val().split('\\').pop();
            $(this).next('.custom-file-label').addClass("selected").html(fileName);
        });


        function show_img_details(img_path){
            $('#img_detail').attr("src", img_path);
            $('#img_detail_modal').modal('toggle');
        }

        function showAlert(){
            if($("#myAlert").find("div#myAlert2").length==0){
                $("#myAlert").append("<div class='alert alert-success alert-dismissable' id='myAlert2'> <button type='button' class='close' data-dismiss='alert'  aria-hidden='true'>&times;</button> Success! Question sent successfully.</div>");
            }
            $("#myAlert").css("display", "");
        }

    </script>

{% endblock %}


{% block content %}

    <div class="mt-5 text-center">
        <h1>Ask A Question</h1>
    </div>
    <form action="#postqn" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group input-group-lg">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-lg">Enter title</span>
            </div>
            <textarea class="form-control" aria-label="With textarea" name="titletxt" rows="1"></textarea>
        <div class="input-group input-group-lg">
        <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroup-sizing-lg">Enter text</span>
        </div>
        <textarea class="form-control" aria-label="With textarea" name="txtbx" rows="10">{% with image_last as ocr_text %}{% with ocr_text.ocrtext_set.last as test %}{{test.text}}{% endwith %}
        {% endwith %} </textarea>
    </div>
        <div class="offset-md-2 col-md-8 my-2">
            <button type="submit" class = "btn btn-primary" name="submitqn" value="showAlert" onclick="showAlert();" >Submit Question</button>
            <div class="container" style="display:none;" id="myAlert">
                <div class="alert alert-success alert-dismissable" id="myAlert2">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    Success! Question sent successfully.
                </div>
            </div>
        </div>
    </form>

    <div class="offset-md-2 col-md-8 my-5" id="image_form">
        <form action="#image_form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <div class="custom-file my-2">
                    {{image_form.image|add_class:"custom-file-input"}}
                    <label class="custom-file-label">{{ image_form.image.label }}</label>
                    {% for error in field.errors %}
                        <span class="badge badge-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-primary">Convert Image to Text</button>
            </fieldset>
        </form>
    </div>


{% endblock %}

Codesk/templates/uploader/multiple.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block extrascript %}
    <script>
        function showAlert(){
            if($("#myAlert").find("div#myAlert2").length==0){
                $("#myAlert").append("<div class='alert alert-success alert-dismissable' id='myAlert2'> <button type='button' class='close' data-dismiss='alert'  aria-hidden='true'>&times;</button> Success! Notes uploaded successfully.</div>");
            }
            $("#myAlert").css("display", "");
        }
    </script>

{% endblock %}

{% block content %}
<body>
<div class="mt-5 text-center">
    <h1>Share A Note</h1>
</div>
<div style="width: 500px; margin: auto;">
    <fieldset name="Multiple Files Upload">
        {% if msg %} {% autoescape off %} {{ msg }} {% endautoescape %} {% endif %}
        <form method="POST" action="/uploadnotes/" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <div class="custom-file my-2">
            <dl>
                <label>Browse and select one or more files</label>
                <input type="file" name="files" autocomplete="off" required multiple>
            </dl>
                </div>
            </fieldset>
                <button type="submit" class = "btn btn-primary" value="showAlert" onclick="showAlert();"> Upload </button>
                <div class="container" style="display:none;" id="myAlert">
                    <div class="alert alert-success alert-dismissable" id="myAlert2">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        Success! Notes uploaded successfully.
                    </div>
                </div>
        </form>
    </fieldset>
</div>
</body>
{% endblock %}